# Generated by Django 4.2.5 on 2023-09-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_list',
            name='pphoto',
            field=models.ImageField(default=2, upload_to='poster'),
            preserve_default=False,
        ),
    ]
